import = ["~/dotfiles/dracula.toml"]

[shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = ["~"]

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[font]
size = 13.0

[window]
startup_mode = "Maximized"
padding = { x = 8, y = 8 }

[selection]
save_to_clipboard = true
